version: "3"
services:
  app:
    restart: always
    container_name: bybit-monitor
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    tty: true
    env_file:
     - .env
    ports:
      - 8080:8080